### ISSUE TITLE
想要合并release里的文件

### ISSUE THREAD

**Issue by JokerJostar** [wangzhaode/llm-export#32]
求教

`embedding.onnx`
`lm.onnx`
`block_[0-23].onnx`
这三类文件分别是什么作用，如果要合并的话只用block吗还是所有的一起，我直接转换chatglm3-6b失败了

**Comment by wangzhaode** [comment]
具体的作用可以看下代码；如果像转换合并的模型就使用`--export`

**Comment by JokerJostar** [comment]
> 具体的作用可以看下代码；如果像转换合并的模型就使用`--export`

 python3 llm_export.py --path ../chatglm3-6b --export --onnx_path ./chatglm2-6b-onnx
The device support i8sdot:0, support fp16:0, support i8mm: 0
Traceback (most recent call last):
  File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 1081, in <module>
    llm_exporter = llm_models[model_type](args)
  File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 562, in __init__
    super().__init__(args)
  File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 511, in __init__
    super().__init__(args)
  File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 90, in __init__
    self.sp_model = spm.SentencePieceProcessor(tokenizer_model)
  File "/home/jostar/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/jostar/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/jostar/.local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

这是sentencepiece的问题吗，我是用requirements.txt安装的

**Comment by Franklinlifangcheng** [comment]
> > 具体的作用可以看下代码；如果像转换合并的模型就使用`--export`
> 
> python3 llm_export.py --path ../chatglm3-6b --export --onnx_path ./chatglm2-6b-onnx The device support i8sdot:0, support fp16:0, support i8mm: 0 Traceback (most recent call last): File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 1081, in llm_exporter = llm_models[model_type](args) File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 562, in **init** super().**init**(args) File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 511, in **init** super().**init**(args) File "/home/jostar/workspace/PycharmProjects/Rk/llm-export/llm_export.py", line 90, in **init** self.sp_model = spm.SentencePieceProcessor(tokenizer_model) File "/home/jostar/.local/lib/python3.10/site-packages/sentencepiece/**init**.py", line 447, in Init self.Load(model_file=model_file, model_proto=model_proto) File "/home/jostar/.local/lib/python3.10/site-packages/sentencepiece/**init**.py", line 905, in Load return self.LoadFromFile(model_file) File "/home/jostar/.local/lib/python3.10/site-packages/sentencepiece/**init**.py", line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
> 
> 这是sentencepiece的问题吗，我是用requirements.txt安装的

请问大佬有没有针对微调后的chatglm3的onnx转换的经验呀
