### ISSUE TITLE
export Chatglm3 fail

### ISSUE THREAD

**Issue by yaoxingwei** [wangzhaode/llm-export#4]
Hello,
I try to export chatglm3 to onnx single model, but got below error. Did I miss some installation flow? Thanks.

ENV:
python3.8.0

CMD：
python -m pip install -r requirements.txt
python llm_export.py --path ~/models/chatglm3-6b/ --export

trigger error：
Traceback (most recent call last):
  File "/home/llm-export/llm_export.py", line 650, in <module>
    llm_exporter.export()
  File "/home/llm-export/llm_export.py", line 222, in export
    torch.onnx.export(
  File "/home//anaconda3/envs/hf/lib/python3.8/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/anaconda3/envs/hf/lib/python3.8/site-packages/torch/onnx/utils.py", line 1587, in _export
    ) = graph._export_onnx(  # type: ignore[attr-defined]
RuntimeError: ONNX export failed. Could not open file or directory: ././onnx/embed_.weight

**Comment by wangzhaode** [comment]
`mkdir onnx` and then do the export
