### ISSUE TITLE
Qwen-1_8B-Chat 模型转换出错

### ISSUE THREAD

**Issue by xhzheng1895** [wangzhaode/llm-export#52]
使用tramsformers==4.31.0时，报错：
```
Traceback (most recent call last):
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 1404, in <module>
    llm_exporter = llm_models[model_type](args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 802, in __init__
    super().__init__(args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 121, in __init__
    self.load_hf(args.path)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 133, in load_hf
    self.tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
  File "/home/xinzhe02/.local/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 784, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.

```

升级transformers到4.37.0，报另一个错：
```
Traceback (most recent call last):
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 1404, in <module>
    llm_exporter = llm_models[model_type](args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 802, in __init__
    super().__init__(args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 122, in __init__
    self.load_model()
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 820, in load_model
    transformer = self.model.transformer
  File "/home/xinzhe02/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'transformer'
```

cmd line: python3 llm_export.py --type Qwen-1_8B-Chat \
	--path ../Qwen1.5-1.8B-Chat \
	--export --export_mnn \
	--onnx_path ./Qwen-1_8B-Chat-Int4-ONNX \
	--mnn_path ./Qwen-1_8B-Chat-Int4-MNN
python version: 3.9.19
其他包除transformers，均follow requirement.txt

**Comment by xhzheng1895** [comment]
phi-2类似的问题，transformers各版本报不同的错...
<4.37.0
```
Traceback (most recent call last):
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 1404, in <module>
    llm_exporter = llm_models[model_type](args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 1142, in __init__
    super().__init__(args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 121, in __init__
    self.load_hf(args.path)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 137, in load_hf
    self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True).float().eval()
  File "/home/xinzhe02/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 525, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/xinzhe02/.local/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1050, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/xinzhe02/.local/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 748, in __getitem__
    raise KeyError(key)
KeyError: 'phi'
```

>=4.37.0
```
Traceback (most recent call last):
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 1404, in <module>
    llm_exporter = llm_models[model_type](args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 1142, in __init__
    super().__init__(args)
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 122, in __init__
    self.load_model()
  File "/data_sdb/demos/mnn-llm/models/llm-export/llm_export.py", line 1147, in load_model
    transformer = self.model.transformer
  File "/home/xinzhe02/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PhiForCausalLM' object has no attribute 'transformer'
```

**Comment by haozixu** [comment]
我猜得用llm_models里面的对应.py替换hf transformers中的实现
