### ISSUE TITLE
无法转换Llama-3.2-3B

### ISSUE THREAD

**Issue by liuxiaotiao** [wangzhaode/llm-export#60]
试图将Llama-3.2-3B转成mnn，运行
python3 llmexport.py --path Llama-3.2-3B-Instruct/ --export mnn --quant_bit 4 --quant_block 128，
，但是遇到如下问题：
💥 Failed load pretrained model 
Error while deserializing header: HeaderTooLarge

**Comment by wangzhaode** [comment]
看起来模型加载失败了，检查一下你的模型路径对不对，是否完整

**Comment by liuxiaotiao** [comment]
你好，我按照流程源码下载llm-export并编译后，模型和llmexport.py文件路径如下：
llm-export
         | - llmexport
         │        | -Llama-3.2-3B-Instruct
         │        | - llmexport.py
无论是是使用相对路径还是绝对路径，都会显示同样的错误

**Comment by wangzhaode** [comment]
有可能是transformers版本有问题，可以尝试安装最新的transformers库再次尝试。如果还有问题请给出你的命令以及所有打印的信息，以及你的transformers版本

**Comment by liuxiaotiao** [comment]
已更新了transformers的版本
transformers 版本: 4.45.1
下载指令：git clone https://www.modelscope.cn/LLM-Research/Llama-3.2-3B-Instruct.git
文件夹路径：llm-export/llmexport/Llama-3.2-3B-Instruct
转换指令：python3 llmexport.py --path Llama-3.2-3B-Instruct --export mnn --quant_bit 4 --quant_block 128
错误内容：
Loading checkpoint shards:   0%|                                                                                                                                                                                               | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|                                                                                                                                                                                               | 0/2 [00:00<?, ?it/s]
💥 Failed load pretrained model 
Traceback (most recent call last):
  File "/home/ubuntu/llm-export/llmexport/llmexport.py", line 1262, in load_pretrained
    self.model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True).float().eval()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4014, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4482, in _load_pretrained_model
    state_dict = load_state_dict(shard_file, is_quantized=is_quantized)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 549, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/llm-export/llmexport/llmexport.py", line 39, in wrapper
    result = func(*args, **kwargs)
  File "/home/ubuntu/llm-export/llmexport/llmexport.py", line 1277, in load_model
    self.load_pretrained(model_path)
  File "/home/ubuntu/llm-export/llmexport/llmexport.py", line 1264, in load_pretrained
    self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True).float().eval()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4014, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4482, in _load_pretrained_model
    state_dict = load_state_dict(shard_file, is_quantized=is_quantized)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 549, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by wangzhaode** [comment]
看你的错误信息还是原始权重加载就失败了，你先检查一下模型目录下的`safetensor`文件有没有完整下载，核对一下SHA256是否一致。

还可以测试一下本地能否正常推理：
```python
import torch
from transformers import pipeline

model_dir = './Llama-3.2-3B-Instruct '   # 修改成你的模型路径

pipe = pipeline(
    "text-generation",
    model=model_dir,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
]
outputs = pipe(
    messages,
    max_new_tokens=256,
)
print(outputs[0]["generated_text"][-1])
```

**Comment by liuxiaotiao** [comment]
使用modelscope download --model llm-research/llama-3.2-3b-instruct --local_dir ./ 重新下载后，safetensor的SHA256值和modelscope上面的是一致的并且可以正常使用，使用
git clone https://www.modelscope.cn/llm-research/llama-3.2-3b-instruct.git 下载模型的safetensor的存在问题。
